### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Alxdu** [Mirko-r/Notepy#3]
ERROR: Could not find a version that satisfies the requirement tkinter (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for tkinter (from -r requirements.txt (line 1)).

Install issue on Ubuntu 21.04 with a fresh install of conda (python=3.7.6)

**Comment by Mirko-r** [comment]
The problem is that :
 - Tkinter is already included in python3
 
If not work try to follow the setup guide for Ubuntu/Debian
I change some things on requirements.txt, try to reclone

**Comment by Alxdu** [comment]
Thanks that fixed the orginal problem.

Now I'm stuck at the last requirement (os_sys)

ERROR: Could not find a version that satisfies the requirement text-editor (from os_sys) (from versions: none)
ERROR: No matching distribution found for text-editor (from os_sys)

Any idea what dependencies could be missing? Thank you

**Comment by Mirko-r** [comment]
Yes, i already know this issue, the text-editor module required by os-sys it removed from pypl, edit the requirements.txt and delete os-sys, then try again

**Comment by Alxdu** [comment]
I should mention I did a fresh reinstall of anaconda to the latest release (python 3.8 and pip 2.1). 
Removing os-sys from requirements completed the install. 

Running python3 notepy.py returns this error:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)
```

**Comment by Mirko-r** [comment]
This is not related to the program, but to your graphic server config

**Comment by Alxdu** [comment]
I understand. I tried that and also reinstalling libxcb but I'm running into the same issue. Running other GUI apps that I had seems to work. 

I'll have to look into this on my end. Thanks
